package org.jspresso.hrsample.ext.model.usage.extension;

import java.util.ArrayList;
import java.util.List;

import org.jspresso.framework.model.component.AbstractComponentExtension;
import org.jspresso.hrsample.ext.model.usage.MUModule;
import org.jspresso.hrsample.ext.model.usage.MUStat;
import org.jspresso.hrsample.ext.model.usage.MUWorkspace;

/**
 * Generated by Jspresso Developer Studio
 */
public class MUStatExtension extends AbstractComponentExtension<MUStat> {

	public MUStatExtension(MUStat component) {
		super(component);

		registerNotificationForwarding(component, MUStat.WORKSPACE, MUStat.ALL_MODULES);
	}

  /**
   * generated by Jspresso Developer Studio
   * 
   * @return
   */
  public List<MUModule> getAllModules() {
    if (getComponent().getWorkspace() != null
        && getComponent().getWorkspace().getLabel()!=null) { //WORKAROUND !!
      return getComponent().getWorkspace().getAllModules();
    }
    else {
      ArrayList<MUModule> modules = new ArrayList<MUModule>();
      for (MUWorkspace w : getComponent().getAllWorkspaces()) {
        for (MUModule m : w.getModules()) {
          fillModules(m, modules);
        }
      }
      return modules;
    }
  }
  private void fillModules(MUModule masterModule, ArrayList<MUModule> allModules) {
    allModules.add(masterModule);
    for (MUModule m : masterModule.getModules()) {
      fillModules(m, allModules);
    }
  }
  
}
