package org.jspresso.hrsample.ext.model.usage.extension;

import java.util.HashSet;
import java.util.Set;

import org.jspresso.framework.model.component.AbstractComponentExtension;
import org.jspresso.hrsample.ext.model.usage.MUModule;
import org.jspresso.hrsample.ext.model.usage.MUStat;
import org.jspresso.hrsample.ext.model.usage.MUWorkspace;

/**
 * Generated by Jspresso Developer Studio
 */
public class MUStatExtension extends AbstractComponentExtension<MUStat> {

	public MUStatExtension(MUStat component) {
		super(component);

		//registerNotificationForwarding(component, MUStat.FIELD, MUStat.COMPUTED_FIELD);
	}

  /**
   * generated by Jspresso Developer Studio
   * 
   * @return
   */
  public Set<MUModule> getAllModules() {
    if (getComponent().getWorkspace() != null) {
      return getComponent().getWorkspace().getModules();
    }
    else {
      HashSet<MUModule> modules = new HashSet<MUModule>();
      for (MUWorkspace w : getComponent().getAllWorkspaces()) {
        modules.addAll(w.getModules());
      }
      return modules;
    }
  }
  
}
