package org.jspresso.hrsample.ext.model.usage.processor;

import org.jspresso.framework.util.bean.integrity.EmptyPropertyProcessor;
import org.jspresso.hrsample.ext.model.usage.MUModule;
import org.jspresso.hrsample.ext.model.usage.MUStat;
import org.jspresso.hrsample.ext.model.usage.MUWorkspace;

/**
 * Generated by Jspresso Developer Studio
 */
public class MUStatProcessors {

  /**
   * generated by Jspresso Developer Studio
   */
  public static class WorkspaceProcessor extends EmptyPropertyProcessor<MUStat, MUWorkspace> {
    
    @Override
    public void postprocessSetter(MUStat stat, MUWorkspace oldWorkpace, MUWorkspace newWorkspace) {
      if (newWorkspace !=null) {
        MUModule m = newWorkspace.getModules().size()>0 ? newWorkspace.getModules().get(0) : null;
        stat.setHistoryModule(m);
      }
      else {
        MUModule m = stat.getAllModules().get(0);
        stat.setHistoryModule(m);
      }
      stat.refresh();
    }

  }

  /**
   * generated by Jspresso Developer Studio
   */
  public static class PeriodProcessor extends EmptyPropertyProcessor<MUStat, String> {

    @Override
    public void postprocessSetter(MUStat stat, String oldPeriod, String newPeriod) {
      stat.refresh();
    }
  }

  /**
   * generated by Jspresso Developer Studio
   */
  public static class HistoryModuleProcessor extends EmptyPropertyProcessor<MUStat, MUModule> {
  
    @Override
    public void postprocessSetter(MUStat stat, MUModule oldPropertyValue, MUModule newPropertyValue) {
      stat.refresh();
    }
  }

}