package org.jspresso.hrsample.ext.model.extension;

import org.jspresso.contrib.model.i18n.extension.TranslatableExtension;
import org.jspresso.hrsample.ext.model.Furniture;

/**
 * Generated by Jspresso Developer Studio.
 */
public class FurnitureExtension extends TranslatableExtension {

  /**
   * Constructs a new <code>FurnitureExtension</code> instance.
   * 
   * @param component
   *          the furniture to extend.
   */
  public FurnitureExtension(Furniture component) {
    super(component);
  }
}
