package org.jspresso.hrsample.ext.model.usage.service;
 
import org.jspresso.framework.model.component.service.EmptyLifecycleInterceptor;
import org.jspresso.framework.model.entity.IEntityFactory;
import org.jspresso.framework.model.entity.IEntityLifecycleHandler;
import org.jspresso.framework.security.UserPrincipal;
import org.jspresso.hrsample.ext.model.usage.MUStat;

/**
 * Generated by Jspresso Developer Studio
 **/
public class MUStatInterceptor extends EmptyLifecycleInterceptor<MUStat> {
  
  @Override
  public boolean onCreate(MUStat stat, IEntityFactory entityFactory,
      UserPrincipal principal, IEntityLifecycleHandler entityLifecycleHandler) {
    
    stat.setPeriod(MUStat.PERIOD_WEEK);
  
    return super.onCreate(stat, entityFactory, principal, entityLifecycleHandler);
  }

}
