package org.jspresso.hrsample.ext.model.usage.service;

import org.jspresso.hrsample.ext.model.usage.MUModule;

/**
 * Generated by Jspresso Developer Studio
 */
public interface MUStatService {

  void refresh();
  MUModule getModule(String moduleId);
  
}