package org.jspresso.hrsample.ext.model.usage.service;

import org.jspresso.hrsample.ext.model.usage.MUModule;
import org.jspresso.hrsample.ext.model.usage.MUWorkspace;
import org.jspresso.hrsample.ext.model.usage.service.MUEvent.EMUEvent;

/**
 * Generated by Jspresso Developer Studio
 */
public interface MUStatService {

  void refresh(EMUEvent event);
  MUModule getModule(String moduleId);
  MUWorkspace getWorkspaceForModule(String moduleId);
  
}