package org.jspresso.hrsample.ext.model.usage.service;

import org.jspresso.framework.model.component.service.IComponentService;

/**
 * Generated by Jspresso Developer Studio
 */
public class MUStatServiceBean implements IComponentService {

}