package org.jspresso.hrsample.ext.model.usage.service;

import org.jspresso.framework.model.component.service.IComponentService;
import org.jspresso.hrsample.ext.model.usage.MUStat;

/**
 * Generated by Jspresso Developer Studio
 */
public class MUStatServiceDelegate implements IComponentService {

  /**
   * generated by Jspresso Developer Studio
   */
  public void loadWorkspaces(MUStat mUStat) {

  }

}